# Generated by Django 5.1.2 on 2024-11-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('proximo', 'Próximo'), ('distante', 'Distante')], default='distante', max_length=10),
        ),
    ]
