# Generated by Django 5.1.2 on 2024-11-05 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_tarefa_prioridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='participantes',
            field=models.ManyToManyField(related_name='tarefas', to=settings.AUTH_USER_MODEL),
        ),
    ]
