# Generated by Django 5.1.2 on 2024-11-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
