# Generated by Django 5.1.2 on 2024-11-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('menu', '0003_tarefa_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='participantes',
            field=models.ManyToManyField(related_name='tarefas', to='login.usuario'),
        ),
    ]
