# Generated by Django 5.1.2 on 2024-11-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='tarefas_arquivos/'),
        ),
    ]
